<?php

function lquery_menu( )
{
	$items = array( );
	
	$items['admin/structure/lquery'] = array(
		 'title' => 'Lquery admin page',
		'description' => 'Here you can edit rights to edit/manipulate queries',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(
			 'lquery_admin' 
		),
		'access arguments' => array(
			 'administer users' 
		) 
	);
	
	$items['lquery/add'] = array(
		 'title' => 'lq_Query creator',
		'description' => 'Adds and forms queries',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'lquery_block_view',
		'access callback' => 'content_priv_check',
		'access arguments' => array(
			 'lq_content_creator' 
		) 
	);
	
	$items['lquery/dummy'] = array(
		 'title' => 'dummy',
		'description' => 'dummy page',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'test_view',
		'access callback' => 'content_priv_check',
		'access arguments' => array(
			 'lq_content_creator' 
		) 
	);
	
	$items['lquery/manage'] = array(
		 'title' => 'lq_Manage queries',
		'description' => 'Manage queries',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'q_manage_block_view',
		'access callback' => 'content_priv_check',
		'access arguments' => array(
			 'lq_content_creator' 
		) 
	);
	
	return $items;
}


function content_priv_check( ) // THIS FUNCTION CHECK IF USER HAS PRIVILEDGE TO SEE AND ACCESS QUERY CREATION PAGES.
{
	global $user;
	
	
	$roles = $user->roles;
	
	$role_allowed = FALSE;
	
	foreach ( $roles as $role )
	{
		if ( $role == 'lq_content_creator' )
		{
			$role_allowed = TRUE;
		}
	}
	
	return $role_allowed;
	
}


//////////////////////////////////////////////////////////////////
///////////// GENERATION OF HELP MESSAGES AROUND THE ENVIRONMENT /
//////////////////////////////////////////////////////////////////

function lquery_help( $path, $arg )
{
	
	if ( $wrapper = file_stream_wrapper_get_instance_by_uri( 'public://' ) )
	{
		$realpath = $wrapper->realpath();
	}
	
	
	switch ( $path )
	{
		case 'admin/help#lquery':
			return '<p>' . t( "This modulle has created a new pofile to be linked to content creators user account.<br><br>Also remember to configure the visibility of query view to themes. By default it is not configured to any theme.<br><br>If CSV export doesn't work, try giving more rights to public:// realpath. That is located at " . $realpath . ". CSVs can be exported under 'manage queries'. Other export formats must be asked from admin of database. CSV is simple array format understood by most spreadsheet programs. Please note that answers are not shown for user if javascript is not on.<br><br>Language of tips at query answering profile has now configuration to select between languages visible to regular user." ) . '</p>';
			break;
		case 'admin/structure/lquery':
			return '<p>' . t( 'Here you can select where to put your query answering view.<br><br> Be aware that using some regions as view point may cause issues. Using those may cause collisions and some parts of UI may become unaccessible. Be cautious!<br><br>Also notice that you can select multiple regions although one view per page is recommended. Usually sidebar is good selection.' ) . '</p>';
			break;
		case 'lquery/add':
			return '<p>' . t( 'This is where you can create queries to lquery module.<br>Remember to update fields before submitting<br>To set query active or remove query, you need to navigate to "Manage queries" page. Note that plain numeric options in list are not allowed. Instead "n2n" is allowed but "1" is not allowed. ' ) . '</p>';
			break;
		case 'lquery/manage':
			return '<p>' . t( 'Here you can manage which query is active and what to destroy. Also it is possible to check answers of query. Checking all the answers works by exporting answers to CVS file.' ) . '</p>';
			break;
	}
}



///////////////////////////////////////////////////
///////// MANAGER /////////////////////////////////
///////////////////////////////////////////////////

function q_manage_block_view( $delta = '' )
{
	drupal_session_start();
	
	if ( !isset( $_SESSION['clicked_button'] ) )
	{
		$_SESSION['clicked_button'] = 0;
	}
	;
	
	if ( !isset( $_SESSION['open_view'] ) )
	{
		$_SESSION['open_view'] = 0;
	}
	;
	
	if ( !isset( $_SESSION['query_to_view'] ) )
	{
		$_SESSION['query_to_view'] = 0;
	}
	;
	
	
	
	$block = array( );
	
	switch ( $_SESSION['open_view'] )
	{
		case 0:
			$content['management_form'] = array(
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				drupal_get_form( 'manage_form' ) 
			);
			
			$block['content'] = $content;
			
			break;
		case 1:
			$content['view_query'] = array(
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				drupal_get_form( 'query_view_form' ) 
			);
			
			return $content;
			
			break;
			
	}
	
	
	return $block;
	
	
	
}
///////////////////////////////////////
/// VIEW  /////////////////////////////  VIEW ANSWERS OF QUERY
/////////////////////////////////////// 

function query_view_form( )
{
	
	$form['go_back'] = array(
		 '#type' => 'submit',
		'#value' => t( 'back' ),
		'#submit' => array(
			 'go_to_manage' 
		) 
	);
	
	
	$active_query = db_query( 'SELECT query_n FROM lquery_index WHERE id = ' . $_SESSION['query_to_view'] )->fetchField();
	
	
	//$columns= db_query('SHOW COLUMNS FROM ' . $table_name)->fetchAll();
	
	$sql_columns  = "SHOW COLUMNS FROM lq_l_" . $active_query;
	$column_names = array( );
	
	$result = db_query( $sql_columns )->fetchAll();
	
	$i = 0;
	
	if ( isset( $result ) )
	{
		foreach ( $result as $s_row )
		{
			$i++;
			if ( $i > 2 )
			{
				array_push( $column_names, $s_row->Field );
			}
		}
	}
	
	$sql_query_results = "SELECT ";
	
	foreach ( $column_names as $insert )
	{
		$sql_query_results .= $insert . ", ";
	}
	
	$sql_query_results = substr( $sql_query_results, 0, -2 );
	
	$sql_query_results .= ' ';
	
	$sql_query_results .= 'FROM ' . 'lq_l_' . $active_query;
	
	
	$sql_results = db_query( $sql_query_results )->fetchAll();
	
	
	///////////////////////////////////////////////////////////////
	///////////////////////////////CSV OFFER 		 //////////////
	///////////////////////////////////////////////////////////////
	
	$form['topic'] = array(
		 '#prefix' => '<h2>',
		'#suffix' => '</h2>',
		'#markup' => t( $active_query ) 
	);
	
	
	$csv_file_dir = 'public://lquery';
	if ( file_prepare_directory( $csv_file_dir, FILE_CREATE_DIRECTORY ) )
	{
		$directory_error = FALSE;
	}
	else
	{
		
		if ( $wrapper = file_stream_wrapper_get_instance_by_uri( 'public://' ) )
		{
			$realpath = $wrapper->realpath();
			
		}
		
		$form['directory_error'] = array(
			 '#prefix' => '<p>',
			'#suffix' => '<p>',
			'#markup' => t( 'Error with creating directory to public file folder. Check priviledges of ' . $realpath . '. Download doesn not work' ) 
		);
		$directory_error         = TRUE;
	}
	
	
	
	
	if ( $directory_error == FALSE )
	{
		$prepared_results = '';
		foreach ( $column_names as $column )
		{
			$prepared_results .= $column . ',';
		}
		
		$prepared_results = substr( $prepared_results, 0, -1 );
		$prepared_results .= "\r\n";
		
		foreach ( $sql_results as $row )
		{
			foreach ( $row as $column )
			{
				if ( $column == NULL )
				{
					$column = 0;
				}
				$prepared_results .= '"' . $column . '",';
			}
			$prepared_results = substr( $prepared_results, 0, -1 );
			$prepared_results .= "\r\n";
		}
		
		$csv_filename = 'lquery_results.csv';
		if ( $file = file_save_data( $prepared_results, 'public://lquery/' . $csv_filename, FILE_EXISTS_REPLACE ) )
		{
			
			
			$link = '<a href="';
			$link .= file_create_url( file_build_uri( '/lquery/' . $csv_filename ) );
			$link .= '">download more detailed CSV spredsheet of query answers</a>';
			
			
			
			$form['link'] = array(
				 '#prefix' => '<p>',
				'#suffix' => '<p>',
				'#markup' => t( $link ) 
			);
		}
		else
		{
			
			$form['error'] = array(
				 '#prefix' => '<h1>',
				'#suffix' => '</h1>',
				'#markup' => t( 'ERROR WITH FILE SAVE' ) 
			);
		}
		
		
		$form['topic'] = array(
			 '#prefix' => '<h2>',
			'#suffix' => '</h2>',
			'#markup' => t( $active_query ) 
		);
		
	}
	return $form;
}

function go_to_manage( $form, &$form_state )
{
	$_SESSION['open_view'] = 0;
}
/////////////////////////////////////////
///  QUERY MANAGE FORM //////////////////
/////////////////////////////////////////
function manage_form( $form, &$form_state )
{
	$content = array( );
	
	$i_query = db_select( 'lquery_index', 'i' )
	//->fields('i', array('query_n'))
		->fields( 'i' );
	//->execute();
	//->fetchAssoc();
	
	$result = $i_query->execute();
	
	$i_query_array = array( );
	
	while ( $record = $result->fetchAssoc() )
	{
		array_push( $i_query_array, $record );
	}
	
	
	$row = array( );
	
	
	$content['array_top'] = array(
		 '#type' => 'markup',
		'#markup' => '<table><tr><th>#ID</th><th>name</th><th>is active</th><th>manage</th></tr>' 
	);
	
	foreach ( $i_query_array as $row )
	{
		
		settype( $content_name, 'string' );
		$content_name = (string) $row['query_n'];
		
		if ( $row['active'] == 0 )
		{
			$active = '<p class="red">no</p>';
		}
		else
		{
			$active = '<p class="green">yes</p>';
		}
		
		$content[$content_name . 'start_of_line'] = array(
			 '#type' => 'markup',
			'#markup' => '<tr><td>' . $row['id'] . '</td><td> ' . $row['query_n'] . '</td><td>' . $active . '</td><td>' 
		);
		
		$content[$content_name . 'button_set'] = array(
			 '#type' => 'submit',
			'#value' => t( 'set active' ),
			'#name' => $row['id'],
			'#submit' => array(
				 'row_set_active' 
			),
			'#button_type' => 'green-button' 
		);
		
		$content[$content_name . 'button_remove'] = array(
			 '#type' => 'submit',
			'#value' => t( 'remove' ),
			'#name' => $row['id'],
			'#submit' => array(
				 'row_remove' 
			),
			'#button_type' => 'red-button' 
		);
		
		$content[$content_name . 'button_view'] = array(
			 '#type' => 'submit',
			'#value' => t( 'check answers' ),
			'#name' => $row['id'],
			'#submit' => array(
				 'view_answers' 
			),
			'#button_type' => 'blue-button' 
		);
		
		$content[$content_name . 'end_of_line'] = array(
			 '#type' => 'markup',
			'#markup' => '</td></tr>' 
		);
		
	}
	
	
	$content['array_end'] = array(
		 '#type' => 'markup',
		'#markup' => '</table>' 
	);
	
	
	$content['remove_all'] = array(
		 '#type' => 'submit',
		'#button_type' => 'red-button',
		'#value' => t( 'Remove all' ),
		'#submit' => array(
			 'Remove_all' 
		) 
	);
	
	$form = $content;
	
	return $form;
}

function view_answers( $form, &$form_state )
{
	$_SESSION['query_to_view'] = $form_state['triggering_element']['#name'];
	$_SESSION['open_view']     = 1;
}

function row_set_active( $form, &$form_state )
{
	$_SESSION['clicked_button'] = $form_state['triggering_element']['#name'];
	
	
	db_update( 'lquery_index' )->fields( array(
		 'active' => 0 
	) )->execute();
	
	
	db_update( 'lquery_index' )->condition( 'id', $_SESSION['clicked_button'], '=' )->fields( array(
		 'active' => 1 
	) )->execute();
}

function row_remove( $form, &$form_state )
{
	$_SESSION['clicked_button'] = $form_state['triggering_element']['#name'];
	
	$query_name = db_query( "SELECT query_n FROM lquery_index WHERE id = :button", array(
		 ':button' => $_SESSION['clicked_button'] 
	) )->fetchField();
	
	$long_name  = 'lq_l_' . $query_name;
	$short_name = 'lq_s_' . $query_name;
	
	$deleted_query = db_delete( 'lquery_index' )->condition( 'id', $_SESSION['clicked_button'] )->execute();
	
	
	
	db_drop_table( $long_name );
	db_drop_table( $short_name );
	
}



function Remove_all( $form, &$form_state )
{
	$query_list = db_query( 'SELECT query_n FROM lquery_index' )->fetchAll();
	if ( $query_list != NULL )
	{
		
		foreach ( $query_list as $name )
		{
			
			$long  = 'lq_l_' . $name->query_n;
			$short = 'lq_s_' . $name->query_n;
			
			db_drop_table( $long );
			db_drop_table( $short );
		}
	}
	
	
	$deleted_index = db_delete( 'lquery_index' )->execute();
	
}

function test_form( $form, &$form_state )
{
	
	$form['testinki'] = array(
		 '#type' => 'submit',
		'#submit' => array(
			 'set_active' 
		) 
	);
	return $form;
}

function set_name( $form, &$form_state )
{
	$_SESSION['clicked_button'] = 1;
}


function test_view( )
{
	global $user;
	
	
	
	$content = array( );
	
	$i_query = db_select( 'lquery_index', 'i' )
	//->fields('i', array('query_n'))
		->fields( 'i' );
	//->execute();
	//->fetchAssoc();
	
	$result = $i_query->execute();
	
	$i_query_array = array( );
	
	
	foreach ( $result as $row )
	{
		$ar = (array) $row;
		
		
	}
	
	
	return 'YAY!';
	
}



//////////////////////////////////////////////////////
/////////////   CONFIG PAGE FOR SELECTING REGIONS ////
//////////////////////////////////////////////////////
function lquery_admin( )
{
	
	$form = array( );
	
	
	$form['language_of_view'] = array(
		 '#type' => 'select',
		'#title' => t( 'Language' ),
		'#description' => 'Select language for query view.',
		'#multiple' => FALSE,
		'#options' => array(
			 0 => t( 'English' ),
			1 => t( 'Suomi' ) 
		) 
	);
	
	
	$form['dummy'] = array(
		 '#markup' => '<br><br>' 
	);
	
	foreach ( list_themes() as $key => $themes )
	{
		
		$form['regions' . $key] = array(
			 '#type' => 'select',
			'#title' => t( $key . ' theme' ),
			'#description' => 'Select regions where to view query',
			'#multiple' => TRUE,
			'#options' => system_region_list( $key ) 
		);
		
	}
	
	return system_settings_form( $form );
}
/////////////////////////////////////////
/////////// QUERY ANSWERING VIEW ////////
/////////////////////////////////////////

function lquery_page_build( &$page )
{
	drupal_session_start();
	
	global $conf;
	global $theme;
	global $user;
	
	if ( !isset( $_SESSION['wants_to_view'] ) )
	{
		$_SESSION['wants_to_view'] = FALSE;
	}
	
	$current_user = session_id();
	
	$active_query = db_query( 'SELECT query_n FROM lquery_index WHERE active = 1' )->fetchField();
	
	if ( $active_query != NULL )
	{
		
		$active_db = 'lq_l_' . $active_query;
		$short_db  = 'lq_s_' . $active_query;
		
		
		$user_list = db_select( $active_db, 'u' )->fields( 'u' )->condition( 'user', $current_user, '=' )->execute()->fetchAll();
	}
	
	
	
	/////////////////////////////////////////////////////
	////////// READ VOTED VALUES ////////////////////////
	/////////////////////////////////////////////////////
	
	
	$current_list_of_regions = $conf['regions' . $theme];
	
	foreach ( $current_list_of_regions as $region_location )
	{
		///   KOUKKU2
		
		if ( $active_query != NULL )
		{
			$table_name = 'lq_l_' . $active_query;
			$user_list  = db_query( 'SELECT user FROM ' . $table_name )->fetchAll();
		}
		
		
		
		if ( !isset( $user_list ) )
		{
			$user_list = array( );
		}
		;
		
		$user_found = FALSE;
		
		if ( $user_list != NULL )
		{
			foreach ( $user_list as $uID )
			{
				
				if ( $uID->user == session_id() ) ///KÄYTTÄJÄN TUNNISTAMINEN
				{
					$user_found = TRUE;
				}
			}
		}
		elseif ( $_SESSION['wants_to_view'] == TRUE )
		{
			$user_found = TRUE;
		}
		
		
		
		if ( $user_list == NULL && $user_found == FALSE )
		{
			$page[$region_location] = drupal_get_form( 'answer_form' );
		}
		elseif ( $user_found == TRUE )
		{
			$_SESSION['wants_to_view'] = FALSE;
			$user_found                = FALSE;
			$db_results                = db_query( 'SELECT * FROM lq_s_' . $active_query )->fetchAll();
			
			
			$array_results = array( );
			$array_names   = array( );
			
			$i = 0;
			
			foreach ( $db_results[0] as $db_name => $temp_value )
			{
				
				$i++;
				
				if ( $i > 3 )
				{
					array_push( $array_names, $db_name );
					array_push( $array_results, $temp_value );
				}
				
				
			}
			
			// jquery canvas
			$language = variable_get( 'language_of_view', 0 );
			
			switch ( $language )
			{
				case 0:
					$query_answers_topic = 'Query answers';
					break;
				case 1:
					$query_answers_topic = 'Kyselyn vastaukset';
					break;
				default:
					$query_answers_topic = 'Query answers';
					break;
					
			}
			
			
			$page[$region_location]['topic'] = array(
				 '#markup' => t( '<h3>' . $query_answers_topic . '</h3>' ) //SUOMENNA
			);
			
			$i = 0;
			
			while ( $i < count( $array_names ) )
			{
				$page[$region_location][$i] = array(
					 '#markup' => t( '<div id="bar" border:1px solid black;><canvas id="query_bar' . $i . '" width="100" height="20"</canvas></div>' ) 
				);
				$i++;
			}
			
			$i     = 0;
			$total = 0;
			foreach ( $array_results as $result )
			{
				$total += $result;
			}
			$n = 0;
			if ( $total > 0 )
			{
				
				while ( $i < count( $array_names ) )
				{
					
					$n = $array_results[$i] * 100 / $total;
					
					
					drupal_add_js( '
					jQuery(document).ready(function()
					{
						var canvas = document.getElementById("query_bar' . $i . '");
						if(canvas.getContext)
						{
							var ctx = canvas.getContext("2d");
							
							ctx.fillStyle = "#AAAAFF";
							ctx.fillRect(0,0, ' . $n . ' ,20);
							ctx.font="bold 11px Arial";
							ctx.fillStyle = "#000000";
							ctx.textBaseline = "top";
							ctx.fillText("' . $array_names[$i] . ':' . $array_results[$i] . '",10,5);
						}
					});', 'inline' );
					
					$i++;
				}
			}
			else
			{
				
				$page[$region_location]['error_div'] = array(
					 '#markup' => t( 'total selections 0 for some reason.' ) 
				);
				
			}
			
		}
		else
		{
			$page[$region_location] = drupal_get_form( 'answer_form' );
			
			
		}
	}
}

function answer_form( $form, &$form_state )
{
	
	global $user;
	
	$account = user_load( session_id() );
	
	$active_query = db_query( 'SELECT query_n FROM lquery_index WHERE active = 1' )->fetchField();
	$full_query   = db_query( 'SELECT query_form FROM lquery_index WHERE active = 1' )->fetchField();
	$multiple     = db_query( 'SELECT multi_select FROM lquery_index WHERE active = 1' )->fetchField();
	
	$column_name = array( );
	
	$table_name    = 'lq_l_' . $active_query;
	$user_answered = FALSE;
	//KOUKKU
	
	
	if ( $active_query != NULL )
	{
		$columns = db_query( 'SHOW COLUMNS FROM ' . $table_name )->fetchAll();
	}
	
	$i            = 0;
	$options_list = array( );
	if ( $active_query != NULL )
	{
		foreach ( $columns as $c_row )
		{
			$i++;
			if ( $i > 2 )
			{
				array_push( $options_list, $c_row->Field );
			}
		}
	}
	
	$language = variable_get( 'language_of_view', 0 );
	
	switch ( $language )
	{
		case 0:
			$reminder             = 'To select multiple options, use &ltctrl&gt-button while selecting.';
			$one_selection        = 'Only one selection is allowed';
			$button_language      = 'Submit';
			$active               = 'NO ACTIVE QUERY';
			$button_view_language = 'View';
			break;
		case 1:
			$reminder             = 'Valitaksesi monta vaihtoehtoa, valitse vaihtoehdot &ltctrl&gt painettuna alas.';
			$one_selection        = 'Vain yksi valinta sallittu';
			$button_language      = 'äänestä';
			$active               = 'EI AKTIIVISTA KYSELYÄ';
			$button_view_language = 'katso';
			break;
		default:
			$reminder             = 'To select multiple options, use &ltctrl&gt-button while selecting.';
			$one_selection        = 'Only one selection is allowed';
			$button_language      = 'Submit';
			$active               = 'NO ACTIVE QUERY';
			$button_view_language = 'View answers';
			break;
	}
	
	if ( $active_query != NULL )
	{
		$form['list'] = array(
			 '#type' => 'select',
			'#title' => t( $active_query ),
			'#options' => $options_list,
			'#description' => t( $full_query ),
			'#multiple' => $multiple 
		);
		
		
		if ( $multiple == TRUE )
		{
			$form['reminder'] = array(
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				'#markup' => t( $reminder ) 
			);
		}
		else
		{
			$form['reminder'] = array(
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				'#markup' => t( $one_selection ) 
			);
		}
		
		$form['submit_answer'] = array(
			 '#type' => 'submit',
			'#value' => t( $button_language ),
			'#submit' => array(
				 'answer_to_query' 
			) 
		);
		
		$form['view_answer'] = array( /// VIEW ANSWERS
			 '#type' => 'submit',
			'#value' => t( $button_view_language ),
			'#submit' => array(
				 'view_query' 
			) 
		);
	}
	else
	{
		$form['error'] = array(
			 '#prefix' => '<p>',
			'#suffix' => '</p>',
			'#markup' => t( $active ) 
		);
	}
	
	return $form;
}

function view_query( $form, &$form_state )
{
	
	$_SESSION['wants_to_view'] = TRUE;
}

function answer_to_query( $form, &$form_state )
{
	$answer_list = array( );
	$answer_list = $form_state['values']['list'];
	
	
	$active_query = db_query( 'SELECT query_n FROM lquery_index WHERE active = 1' )->fetchField();
	$full_query   = db_query( 'SELECT query_form FROM lquery_index WHERE active = 1' )->fetchField();
	$multiple     = db_query( 'SELECT multi_select FROM lquery_index WHERE active = 1' )->fetchField();
	
	$column_name = array( );
	
	$table_name_l = 'lq_l_' . $active_query;
	$table_name_s = 'lq_s_' . $active_query;
	
	if ( $active_query != NULL )
	{
		$columns = db_query( 'SHOW COLUMNS FROM ' . $table_name_l )->fetchAll();
	}
	
	$i            = 0;
	$options_list = array( );
	if ( $active_query != NULL )
	{
		foreach ( $columns as $c_row )
		{
			$i++;
			if ( $i > 2 )
			{
				array_push( $options_list, $c_row->Field );
			}
		}
	}
	
	$names_of_columns_to_be_voted = array( );
	
	foreach ( $answer_list as $selected )
	{
		array_push( $names_of_columns_to_be_voted, $options_list[$selected] );
	}
	;
	
	
	
	global $user;
	
	$fields  = array( );
	$account = user_load( session_id() ); //KERÄTÄÄNKÖ VÄÄRÄ KOODI???
	
	
	$fields['user'] = session_id();
	
	foreach ( $names_of_columns_to_be_voted as $col )
	{
		$fields[$col] = 1;
	}
	;
	
	
	
	/////////////////////////////////////////////////////
	////////////    ANSWER TO LONG TABLE ////////////////
	/////////////////////////////////////////////////////
	
	$long_sql = 'INSERT INTO ' . $table_name_l . ' (';
	
	while ( $column_name = current( $fields ) )
	{
		$long_sql .= ' "' . key( $fields ) . '",';
		
		next( $fields );
	}
	
	$long_sql = mb_substr( $long_sql, 0, -1, 'UTF-8' );
	
	$long_sql .= ' ) VALUES (';
	
	
	foreach ( $fields as $insert_value )
	{
		$long_sql .= " '" . $insert_value . "',";
	}
	
	$long_sql = mb_substr( $long_sql, 0, -1, 'UTF-8' );
	
	$long_sql .= ' )';
	
	
	$long_result = db_query( $long_sql );
	
	//db_query("INSERT INTO lq_l_nimitin21 ( user ) VALUES ( 'u-RZ5y8KStMsTeQWxK_WLgF4qqAwWlqrSfe09CWW_FE')");
	
	
	////////////////////////////////////////////////////////////
	/////////////// SHORT TABLE UPDATE /////////////////////////
	////////////////////////////////////////////////////////////
	
	//$short_values = array();
	
	
	foreach ( $names_of_columns_to_be_voted as $col )
	{
		$short_sql = 'SELECT SUM( "' . $col . '" ) AS amount FROM ' . $table_name_s;
		
		$short_result = db_query( $short_sql )->fetchField();
		
		
		$new_value    = $short_result + 1;
		$short_update = 'UPDATE ' . $table_name_s . " SET " . $col . "='" . $new_value . "' WHERE id='1'";
		
		
		$short_result = db_query( $short_update );
	}
	
}
//////////////////////////////////////////////////////
///////////// FORM TO CREATE QUERY ///////////////////
//////////////////////////////////////////////////////



function lquery_block_view( )
{
	
	drupal_session_start();
	
	//STARTING DEFINATIONS OF PAGE
	
	$default_name_of_query = 'Here goes short name of query';
	
	$title = t( 'Query options' );
	
	$attributes = array(
		 'id' => 'query-list',
		'class' => 'query_class' 
	);
	
	
	$name_of_the_query = 'Default name'; //jäljitä merkitsevyys
	$question          = 'question';
	
	
	
	// $_SESSION TO USE
	if ( !isset( $options ) )
	{
		$options = array( );
	}
	;
	
	if ( !isset( $_SESSION['injection'] ) )
	{
		$_SESSION['injection'] = 0;
	}
	;
	if ( !isset( $_SESSION['value_reserved'] ) )
	{
		$_SESSION['value_reserved'] = 0;
	}
	;
	if ( !isset( $_SESSION['error'] ) )
	{
		$_SESSION['error'] = 0;
	}
	;
	if ( !isset( $_SESSION['injection'] ) )
	{
		$_SESSION['injection'] = 0;
	}
	;
	if ( !isset( $_SESSION['numeric_error'] ) )
	{
		$_SESSION['numeric_error'] = 0;
	}
	;
	
	if ( !isset( $_SESSION['listing'] ) )
	{
		$_SESSION['listing'] = array( );
	}
	;
	if ( !isset( $_SESSION['multiselect_radio'] ) )
	{
		$_SESSION['multiselect_radio'] = 0;
	}
	;
	
	
	if ( !isset( $_SESSION['listing'] ) )
	{
		$_SESSION['listing'] = array( );
	}
	;
	sort( $_SESSION['listing'] );
	$options =& $_SESSION['listing'];
	
	///////////////////////////////////////////////////////////////////////////
	//////////////////  #1 $block add query   /////////////////////////////////
	///////////////////////////////////////////////////////////////////////////
	
	
	
	$block['subject'] = t( 'Query subject' );
	$block['content'] = array(
		 '#markup' => 'Query markup',
		'#title' => t( 'Query title' ) 
	);
	
	
	$error  = '';
	$Verror = '';
	$Nerror = '';
	$Ierror = '';
	
	if ( $_SESSION['injection'] == TRUE )
	{
		$Ierror                = '<font color="red"> <table><tr><th>:::WARNING! MALICIOUS INPUT DETECTED:::</th></tr></table> </font>';
		$_SESSION['injection'] = FALSE;
	}
	
	if ( $_SESSION['error'] == TRUE )
	{
		$error             = '<font color="red"> <table><tr><th>:::ERROR IN INPUT:::</th></tr></table> </font>';
		$_SESSION['error'] = FALSE;
	}
	if ( $_SESSION['value_reserved'] == TRUE )
	{
		$Verror                     = '<font color="red"> <table><tr><th>:::VALUE RESERVED:::</th></tr></table> </font>';
		$_SESSION['value_reserved'] = FALSE;
	}
	if ( $_SESSION['numeric_error'] == TRUE )
	{
		$Nerror                    = '<font color="red"> <table><tr><th>:::NO PLAIN NUMERIC VALUES:::</th></tr></table> </font>';
		$_SESSION['numeric_error'] = FALSE;
	}
	
	$_SESSION['error'] = 0;
	
	
	/////////////////////////////////// LIST OPTION REMOVING HTML FORMING
	
	$block = array(
		 '#prefix' => '<p>',
		'#suffix' => '</p>',
		
		'content' => array(
			
			 'error' => array(
				 '#prefix' => '<e>',
				'#suffix' => '</e>',
				'#markup' => $error 
			),
			'Verror' => array(
				 '#prefix' => '<e>',
				'#suffix' => '</e>',
				'#markup' => $Verror 
			),
			'Nerror' => array(
				 '#prefix' => '<e>',
				'#suffix' => '</e>',
				'#markup' => $Nerror 
			),
			
			'Ierror' => array(
				 '#prefix' => '<e>',
				'#suffix' => '</e>',
				'#markup' => $Ierror 
			),
			
			'q_name' => array( //name form
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				drupal_get_form( 'q_name_form' ) 
			),
			
			
			'q_query' => array(
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				drupal_get_form( 'q_query_long' ) //query form
			),
			
			///////////////    MORE CLEVER LISTING NEEDED   KOUKKU
			
			'clist' => array(
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				drupal_get_form( 'clist' ) 
			),
			
			'new_option' => array(
				 '#prefix' => '<p>',
				'#suffix' => '</p>',
				drupal_get_form( 'query_form' ) // CALLS FOR FORM DEFINATIONS
				//testi();
				
				
			) 
			
			
		) 
		
		
	);
	
	return $block;
}

function clist( $form, &$form_state )
{
	$content['option_topic'] = array(
		 '#prefix' => '<p>',
		'#suffix' => '</p>',
		'#markup' => t( 'LIST OF OPTIONS<br>' ) 
	);
	
	$content['start_of_table'] = array(
		 '#prefix' => '<table><tr><th>option name</th><th>remove</th><tr>' 
	);
	
	
	foreach ( $_SESSION['listing'] as $value )
	{
		
		
		$content[$value . 'option'] = array(
			 '#prefix' => '<tr><td>',
			'#suffix' => '</td>',
			'#markup' => t( $value ) 
		);
		
		$content[$value . 'button_set'] = array(
			
			 '#type' => 'submit',
			'#value' => t( 'remove' ),
			'#name' => $value,
			'#prefix' => '<td>',
			'#suffix' => '</td></tr>',
			'#submit' => array(
				 'remove_option' 
			),
			'#button_type' => 'red-button' 
		);
	}
	
	$content['end of list'] = array(
		 '#suffix' => '</table>' 
	);
	return $content;
}

function remove_option( $form, &$form_state )
{
	$_SESSION['clicked_button'] = $form_state['triggering_element']['#name'];
	
	
	foreach ( array_keys( $_SESSION['listing'], $_SESSION['clicked_button'] ) as $key )
	{
		unset( $_SESSION['listing'][$key] );
	}
	
	
}



function q_name_form( $form, &$form_state )
{
	
	
	
	if ( !isset( $_SESSION['name'] ) )
	{
		
		$_SESSION['name'] = 'Here goes short name of query';
		$value            = $_SESSION['name'];
	}
	else
	{
		$value = $_SESSION['name'];
	}
	
	$form['query_name'] = array(
		 '#type' => 'textfield', //SHORT NAME OF QUERY
		'#default_value' => $value,
		'#size' => 64,
		'#maxlength' => 64,
		'#required' => TRUE,
		'#title' => t( 'Name of query has limit of 64 characters' ) 
	);
	
	$form['update_name'] = array(
		 '#type' => 'submit',
		'#value' => t( 'Update name' ),
		'#submit' => array(
			 'query_form_update_name' 
		) 
	);
	return $form;
}

function q_query_long( $form, &$form_state )
{
	
	if ( !isset( $_SESSION['full_query'] ) )
	{
		$_SESSION['full_query'] = 'Write your query here';
		$query_long             = $_SESSION['full_query'];
	}
	else
	{
		$query_long = $_SESSION['full_query'];
	}
	
	$form['query_text'] = array(
		 '#type' => 'textfield', //exact query to be presented for ppl
		'#default_value' => $query_long,
		'#size' => 64,
		'#maxlength' => 255,
		'#required' => TRUE,
		'#title' => t( 'Full description of query has limit of 255 characters' ) 
	);
	
	$form['update_query'] = array(
		 '#type' => 'submit',
		'#value' => t( 'Update query' ),
		'#submit' => array(
			 'query_form_update_query_text' 
		) 
	);
	
	return $form;
}


function query_form( $form, &$form_state ) // HERE IS THE FORM FOR CREATING QUERYS
	
//UPDATE TEXTFIELDS TO READ CONTENT FROM $_SESSION['q_options']
{
	
	
	$form['query_modifier'] = array(
		 '#type' => 'textfield', //variable goes to list of options
		'#default_value' => 'Here you can write addable option name',
		'#title' => t( 'query modifier' ) 
	);
	$form['add_to_list']    = array(
		 '#type' => 'submit',
		'#value' => t( 'Add to list' ),
		'#submit' => array(
			 'query_form_add_to_list' 
		) 
	);
	
	
	
	$active = array(
		 0 => t( 'single' ),
		1 => t( 'multi' ) 
	);
	
	$form['multiselect']  = array(
		 '#type' => 'radios', //SELECTION TO MODIFY TYPE OF QUERY FROM SINGLE SELECT TO MULTI SELECT
		'#title' => t( 'multiselect or singleselect' ),
		'#description' => t( 'Do you want to select multiple selections or just one selection while voting?' ),
		'#options' => $active,
		'#default_value' => $_SESSION['multiselect_radio'] 
	);
	$form['update_multi'] = array(
		 '#type' => 'submit',
		'#value' => t( 'Update selection mode' ),
		'#submit' => array(
			 'query_update_selection' 
		) 
	);
	////////////////////////////////////////////////////////////////////////////////////////////////
	$form['dummy']        = array(
		 '#markup' => t( '<br><hr>' ) 
	); //USED TO TIDY VISUAL APPEREANCE OF FORM
	////////////////////////////////////////////////////////////////////////////////////////////////
	
	
	//LAST TWO BUTTONS TO EITHER CANCEL ALL MODIFICATIONS OR UPDATE QUERY TO DATABASE
	$form['clear_list']   = array(
		 '#type' => 'submit',
		'#value' => t( 'Clear the query' ),
		'#submit' => array(
			 'query_form_clear_list' 
		) 
	);
	$form['submit_to_db'] = array(
		 '#type' => 'submit',
		'#value' => t( 'Submit query' ),
		'#submit' => array(
			 'query_form_submit_to_db' 
		) 
	);
	
	return $form;
}

//////////////////////////////////////////////
//// SUBMIT BUTTONS //////////////////////////
//////////////////////////////////////////////

function query_update_selection( $form, &$form_state )
{
	$_SESSION['multiselect_radio'] = $form_state['values']['multiselect'];
}

function query_form_clear_list( $form, &$form_state )
{
	session_unset();
}

function query_form_update_name( $form, &$form_state )
{
	
	
	
	$query_list = db_query( 'SELECT query_n FROM lquery_index' )->fetchObject();
	
	$error = FALSE;
	
	$search_val = preg_replace( '/<[^>]*>/', '', $form_state['values']['query_name'] );
	
	
	
	if ( preg_match( '/[\x{80}-\x{A0}' . // Non-printable ISO-8859-1 + NBSP
		'\x{AD}' . // Soft-hyphen
		'\x{2000}-\x{200F}' . // Various space characters
		'\x{2028}-\x{202F}' . // Bidirectional text overrides
		'\x{205F}-\x{206F}' . // Various text hinting characters
		'\x{FEFF}' . // Byte order mark
		'\x{FF01}-\x{FF60}' . // Full-width latin
		'\x{FFF9}-\x{FFFD}' . // Replacement characters
		'\x{0}]/u', // NULL byte
		$search_val ) )
	{
		$_SESSION['error']     = TRUE;
		$_SESSION['injection'] = TRUE;
		$error                 = TRUE;
	}
	
	
	
	if ( $error != TRUE && $query_list != NULL )
	{
		
		foreach ( $query_list as $name )
		{
			if ( $name == $search_val )
			{
				$error                      = TRUE;
				$_SESSION['error']          = TRUE;
				$_SESSION['value_reserved'] = TRUE;
			}
		}
		
		if ( $error != TRUE )
		{
			$_SESSION['name'] = $search_val;
		}
	}
	elseif ( $error != TRUE && $query_list == NULL )
	{
		$_SESSION['name'] = $search_val;
	}
	
}

function query_form_update_query_text( $form, &$form_state )
{
	
	$search_val = $form_state['values']['query_text'];
	
	if ( preg_match( '/[\x{80}-\x{A0}' . // Non-printable ISO-8859-1 + NBSP
		'\x{AD}' . // Soft-hyphen
		'\x{2000}-\x{200F}' . // Various space characters
		'\x{2028}-\x{202F}' . // Bidirectional text overrides
		'\x{205F}-\x{206F}' . // Various text hinting characters
		'\x{FEFF}' . // Byte order mark
		'\x{FF01}-\x{FF60}' . // Full-width latin
		'\x{FFF9}-\x{FFFD}' . // Replacement characters
		'\x{0}]/u', // NULL byte
		$search_val ) )
	{
		$_SESSION['injection'] = TRUE;
		$_SESSION['error']     = TRUE;
	}
	
	if ( $_SESSION['error'] != TRUE )
	{
		$_SESSION['full_query'] = $form_state['values']['query_text'];
	}
}

function query_form_submit_to_db( $form, &$form_state )
{
	$i = 0;
	foreach ( $_SESSION['listing'] as $list_option )
	{
		$i += 1;
	}
	
	
	//TO UPDATE OF RADIOS
	//$_SESSION['multiselect_radio'] = $form_state['values']['multiselect'];
	
	//ADD TO INDEX TABLE
	$id = db_insert( 'lquery_index' )->fields( array(
		 'query_n' => $_SESSION['name'],
		'query_form' => $_SESSION['full_query'],
		'multi_select' => $_SESSION['multiselect_radio'] 
	) )->execute();
	///////////////////////////////
	//CREATE QUERY ANSWER TABLES///
	///////////////////////////////
	
	///LONG
	$fields = array(
		 'id' => array(
			 'type' => 'serial',
			'unsigned' => TRUE,
			'not null' => TRUE,
			'size' => 'big' 
		),
		'user' => array(
			 'type' => 'text',
			'size' => 'small' 
		) 
	);
	
	foreach ( $_SESSION['listing'] as $key )
	{
		$fields[$key] = array(
			 'type' => 'int',
			'size' => 'tiny',
			'not null' => FALSE 
		);
	}
	
	$long_schema = array(
		 'description' => 'Table where all answers are fully stored' 
	);
	
	$long_schema['fields'] = $fields;
	
	$long_schema['primary key'] = array(
		 'id' 
	);
	
	
	
	$table_name = 'lq_l_' . $_SESSION['name'];
	
	
	db_create_table( $table_name, $long_schema );
	
	///SHORT
	
	$short_schema = array(
		 'description' => 'short table of answers' 
	);
	
	$fields_short = array(
		 'id' => array(
			 'type' => 'serial',
			'unsigned' => TRUE,
			'not null' => TRUE,
			'size' => 'big' 
		),
		'name' => array(
			 'type' => 'text',
			'size' => 'tiny' 
		),
		'query' => array(
			 'type' => 'text',
			'size' => 'tiny' 
		) 
	);
	
	
	foreach ( $_SESSION['listing'] as $key )
	{
		$fields_short[$key] = array(
			 'type' => 'int',
			'size' => 'big',
			'not null' => FALSE,
			'default' => 0 
		);
	}
	
	$short_schema['fields'] = $fields_short;
	
	$short_schema['primary key'] = array(
		 'id' 
	);
	
	$short_name = 'lq_s_' . $_SESSION['name'];
	
	
	db_create_table( $short_name, $short_schema );
	
	//////////////////  INITIALIZE OF SHORT TABLE IS NEEDED
	$name       = $_SESSION['name'];
	$short_init = "INSERT INTO " . $short_name . " ( name ) VALUES ( '" . $name . "' )";
	db_query( $short_init );
	
}

function query_form_add_to_list( $form, &$form_state )
{
	
	$argument = $form_state['values']['query_modifier'];
	////// KOUKKU regexp
	if ( preg_match( '/[\x{80}-\x{A0}' . // Non-printable ISO-8859-1 + NBSP
		'\x{AD}' . // Soft-hyphen
		'\x{2000}-\x{200F}' . // Various space characters
		'\x{2028}-\x{202F}' . // Bidirectional text overrides
		'\x{205F}-\x{206F}' . // Various text hinting characters
		'\x{FEFF}' . // Byte order mark
		'\x{FF01}-\x{FF60}' . // Full-width latin
		'\x{FFF9}-\x{FFFD}' . // Replacement characters
		'\x{0}]/u', // NULL byte
		$argument ) )
	{
		$_SESSION['injection'] = TRUE;
		$_SESSION['error']     = TRUE;
	}
	
	
	
	
	
	$argument = $form_state['values']['query_modifier'];
	if ( is_numeric( $argument ) )
	{
		$_SESSION['error']         = 1;
		$_SESSION['numeric_error'] = 1;
	}
	;
	
	settype( $argument, "string" );
	//drupal_set_message( gettype($argument) );
	
	if ( !isset( $_SESSION['listing'] ) )
	{
		$_SESSION['listing'] = array( );
		
	}
	;
	if ( $_SESSION['error'] != 1 )
	{
		array_push( $_SESSION['listing'], $argument );
		sort( $_SESSION['listing'] );
	}
	
	
}

function query_form_remove_from_list( $form, &$form_state )
{
	$variable = $form_state['values']['query_modifier'];
	
	
	
	
	$reversed = array_flip( $_SESSION['listing'] );
	unset( $reversed[$variable] );
	
	$reversed = array_flip( $reversed );
	sort( $reversed );
	$_SESSION['listing'] = NULL;
	$_SESSION['listing'] = $reversed;
	
	
	drupal_set_message( var_dump( $_SESSION['listing'] ) );
	
	drupal_set_message( $variable );
}


?>
